CREATE TABLE Author
(
	ID INT IDENTITY (1,1) NOT NULL,
	Nick VARCHAR(100) NOT NULL,
	CONSTRAINT PK_Author_IDAuthor PRIMARY KEY CLUSTERED (ID)
);
GO

CREATE TABLE Category
(
	ID INT IDENTITY (1,1) NOT NULL,
	[Name] VARCHAR(100) NOT NULL,
	CONSTRAINT PK_Category_ID PRIMARY KEY CLUSTERED (ID)
);
GO

CREATE TABLE Book
(
	ID INT IDENTITY (1,1) NOT NULL,
	Title VARCHAR(100) NOT NULL,
	IDAuthor INT NOT NULL,
	IDCategory INT NULL,
	CONSTRAINT PK_Book_ID PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT FK_Book_IDAuthor FOREIGN KEY (IDAuthor) REFERENCES Author (ID),
	CONSTRAINT FK_Book_IDCategory FOREIGN KEY (IDCategory) REFERENCES Category(ID)
);
GO

CREATE TABLE Person
(
	ID INT IDENTITY (1,1) NOT NULL,
	DocumentNumber VARCHAR(8) NOT NULL,
	Fullname VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	PhoneNumber INT NULL,
	CONSTRAINT PK_Person_ID PRIMARY KEY CLUSTERED (ID)
);
GO

CREATE TABLE Loan
(
	ID INT IDENTITY (1,1) NOT NULL,
	IDPerson INT NOT NULL,
	IDBook INT NOT NULL,
	StartDate DATE NOT NULL,
	AgreedDate DATE NOT NULL,
	ReturnDate DATE NULL,
	Returned BIT NOT NULL DEFAULT 0,
	CONSTRAINT PK_Loan_ID PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT FK_Loan_IDPerson FOREIGN KEY (IDPerson) REFERENCES Person (ID),
	CONSTRAINT FK_Loan_IDBook FOREIGN KEY (IDBook) REFERENCES Book (ID)
);
GO
